# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish to npm

on:
  # Manual trigger with version bump type
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Semver bump type'
        required: false
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major
      registry:
        description: 'Registry URL for publish'
        required: false
        default: 'https://registry.npmjs.org/'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.repository.default_branch }}
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: ${{ inputs.registry || 'https://registry.npmjs.org/' }}
      - name: Install and test
        run: |
          npm ci
          npm test
      - name: Configure git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Bump version and create tag
        env:
          RELEASE_TYPE: ${{ inputs.release_type || 'patch' }}
        run: |
          npm version "$RELEASE_TYPE" -m "chore(release): %s [skip ci]"
      - name: Push commit and tags
        run: |
          git push origin HEAD:${{ github.event.repository.default_branch }} --follow-tags
      - name: Set up .npmrc for authentication
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          REGISTRY=${{ inputs.registry || 'https://registry.npmjs.org/' }}
          npm publish --access public --registry "$REGISTRY"
